### ISSUE TITLE
youtube-dl to yt-dlp

### ISSUE THREAD

**Issue by Sergio1603** [Screenly/Anthias#1841] opened 2023-11-27 17:02 UTC
Good morning, I've uploaded the requirement.txt file and the utils.py file from this site, but I still encounter the same error. I'm using 2023-05-03-raspios-bullseye-arm64-lite, and I've tried to follow your guides, but the error persists when I try to load my videos from YouTube. The error message is: Server Error: Command '['youtube-dl', '-e', 'https://youtu.be/xr2kWPlQqns']' returned non-zero exit status 1. What could I try?"
![Schermata del 2023-11-27 17-55-53](https://github.com/Screenly/Anthias/assets/37803158/1cdd5824-21f5-41b0-afb9-5814d345dd68)

**Comment by nicomiguelino** [comment] 2023-11-27 17:14
This issue is a duplicate of Screenly/Anthias#1779.
Check out Screenly/Anthias#1840 for the ongoing PR.

You can test the changes on your Pi while it's still not merged.
Feel free to reply back if you need any help.

**Comment by Sergio1603** [comment] 2023-11-28 13:55
Certo, ecco la traduzione in inglese del tuo testo:

"Hello Nicomiguelino, I've modified the requirements.txt file as explained, and also the utils.py file as recommended here. I'm using a 64-bit Bullseye operating system on Raspberry Pi 4. What else can I modify to make YouTube work? Thanks again." @nicomiguelino

**Comment by nicomiguelino** [comment] 2023-12-11 16:14
@Sergio1603, check out this PR for the fixes (although it's not yet merged): https://github.com/Screenly/Anthias/pull/1840

**Closed as completed** 2023-12-11 16:14 UTC
