### ISSUE TITLE
youtub-dl to yt-dlp 

### ISSUE THREAD

**Issue by Sergio1603** [Screenly/Anthias#1842] opened 2023-11-29 20:42 UTC
Good evening, I tried using Screenly/Anthias with YouTube. I replaced 'youtube-dl' with 'yt-dlp', followed various guides by modifying the 'requirements.txt' and 'utils.py' files. I tested it on different versions of the Raspberry Pi operating system. My only doubt concerns the incorrect reconstruction of Docker after the various modifications. Thank you if you can provide assistance.
(Raspberry pi 4b)

![285950463-1cdd5824-21f5-41b0-afb9-5814d345dd68](https://github.com/Screenly/Anthias/assets/37803158/8a653b2f-62b8-445c-9fb0-997fdcb39b52)

**Comment by extremeskillz** [comment] 2023-12-02 13:29
I believe they have an open ticket on this. I have the same issue as well. Currently I just download the YT video and upload it to Anthias to play it.

**Comment by Sergio1603** [comment] 2023-12-02 14:42
Hi, I'm doing this too for now

**Comment by nicomiguelino** [comment] 2023-12-11 16:13
Duplicate of 1779

**Closed by nicomiguelino** 2023-12-11 16:13 UTC
